### ISSUE TITLE
Posible error en un concepto de un objetivo de la semana 4

### ISSUE THREAD

**Issue by jmv74211** [JJ/CC-18-19#138]
En los objetivos de la semana 4, hay un objetivo que dice:

- Entender por qué no se hace `git pull` sino `git pull --rebase` y como arreglarlo en ese caso usando `git squash`.

He estado buscando y no existe un comando `git squash`. 

Existe el concepto de hacer un squash de varios commits pero utilizando la orden `git rebase -i `, así que como sugerencia, modificaría dicho objetivo y en lugar de poner `git squash`, pondría `git rebase -i`

**Comment by JJ** [comment]
Tienes razón, y culpa mía por no haberlo aclarado. Te agradecería que
hicieras un PR de esa sesión, puedes modificarlo igual que el resto.
